project:
  type: website
website:
  title: "Abdullah Zeeshan | Portfolio"
  favicon: images/profile.png
  site-url: https://4bdullah7eeshan.github.io
  description: "Portfolio"
  navbar:
    title: "Abdullah Zeeshan"
    search: true
    tools:
      - icon: github
        href: https://github.com/4bdullah7eeshan
      - icon: rss
        href: index.xml
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
    pinned: false
    collapse: true
    collapse-below: lg
    toggle-position: left
  reader-mode: true
  back-to-top-navigation: true
  page-footer:
    left: "© 2024-present, Abdullah Zeeshan"
    center: |
      Made with &hearts; using [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)
    right:
      - icon: github
        href: https://github.com/4bdullah7eeshan
      - icon: rss
        href: index.xml
    border: true
format:
  html:
    theme: cosmo
    toc: true
    page-layout: full


