project:
  type: website
  output-dir: _site

website:
  title: "Abdullah Zeeshan"
  description: "Personal Blog"
  site-url: https://4bdullah7eeshan.github.io
  repo-url: https://github.com/4bdullah7eeshan/4bdullah7eeshan.github.io
  repo-branch: main
  issue-url: https://github.com/4bdullah7eeshan/4bdullah7eeshan.github.io/issues

  favicon: images/favicon.png 
  search:
    location: navbar
    type: overlay
  navbar: 
    background: light
  sidebar:
    style: "docked"
    contents: posts/*
  page-footer:
    background: light
    left: |
      Website created with
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    center:
      - icon: twitter
        href: https://twitter.com/4bdullah7eeshan
      - icon: github
        href: https://github.com/4bdullah7eeshan
      - icon: instagram
        href: https://instagram.com/4bdullah7eeshan
    right: "© 2024-present, Abdullah Zeeshan"
  page-navigation: true
  reader-mode: true
  back-to-top-navigation: true

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme.scss]
    toc: true
    css: style.css

